# =============================================================================
# ManagedDatabaseProvider — control plane never hosts customer tables
# =============================================================================
from __future__ import annotations

from typing import Protocol
from uuid import UUID


class ManagedDatabaseProvider(Protocol):
    async def create_database(
        self, organization_id: UUID, workspace_id: UUID, *, size_mb: int
    ) -> dict: ...

    async def delete_database(self, database_id: str) -> None: ...

    async def rotate_credentials(self, database_id: str) -> dict: ...

    async def create_readonly_user(self, database_id: str) -> dict: ...

    async def create_schema_admin_user(self, database_id: str) -> dict: ...

    async def get_connection_info(self, database_id: str) -> dict: ...

    async def health_check(self, database_id: str) -> dict: ...

    async def backup_status(self, database_id: str) -> dict: ...

    async def execute_admin_ddl(self, database_id: str, sql: str) -> None: ...

    async def execute_admin_dml(self, database_id: str, sql: str, params: dict | None = None) -> None: ...
