apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zent
  labels:
    app.kubernetes.io/name: zent
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - app.example.com
      secretName: zent-tls
  rules:
    - host: app.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portal
                port:
                  name: http
