# =============================================================================
# Knowledge V2 — Phase A re-exports (not wired into the ingestion engine)
# =============================================================================
from src.core.domain.knowledge_v2 import (
    BoundingBox,
    CharRange,
    ChunkType,
    DocumentChangeKind,
    DocumentChunk,
    DocumentFigure,
    DocumentIntegrityError,
    DocumentPage,
    DocumentSection,
    DocumentSummary,
    DocumentTable,
    DocumentVersion,
    KnowledgeCorpus,
    KnowledgeEntity,
    KnowledgeEvidence,
    KnowledgeFact,
    KnowledgeObjectStatus,
    KnowledgeRelationship,
    KnowledgeRelationshipKind,
    RelationshipEndpoint,
    SectionSummary,
    StructuredBlock,
    StructuredBlockKind,
    StructuredContentType,
    StructuredDocument,
    inferred_is_not_approved,
)

__all__ = [
    "BoundingBox",
    "CharRange",
    "ChunkType",
    "DocumentChunk",
    "DocumentChangeKind",
    "DocumentFigure",
    "DocumentIntegrityError",
    "DocumentPage",
    "DocumentSection",
    "DocumentSummary",
    "DocumentTable",
    "DocumentVersion",
    "KnowledgeCorpus",
    "KnowledgeEntity",
    "KnowledgeEvidence",
    "KnowledgeFact",
    "KnowledgeObjectStatus",
    "KnowledgeRelationship",
    "KnowledgeRelationshipKind",
    "RelationshipEndpoint",
    "SectionSummary",
    "StructuredBlock",
    "StructuredBlockKind",
    "StructuredContentType",
    "StructuredDocument",
    "inferred_is_not_approved",
]
